apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: burrnode-gau5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: burrnode-gau5
    app.kubernetes.io/part-of: burrnode
  name: burrnode-gau5
  namespace: burrzinga-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: burrnode-gau5
    weight: null
status: {}
